### ISSUE TITLE
Set protocol (https?)

### ISSUE THREAD

**Issue by valgaze** [opentsdb-js/opentsdb.js#5]
Is there any flag/setting to use http[**s**]? (If not, see PR in [opentsdb-js/url](https://github.com/opentsdb-js/url) where this change would probably need to live if implemented: https://github.com/opentsdb-js/url/issues/2)

------

## [The current get implementation calls this.url()](https://github.com/opentsdb-js/client/blob/master/lib/index.js#L301):
![https://github.com/opentsdb-js/client/blob/master/lib/index.js#L301](https://cloud.githubusercontent.com/assets/1396559/21623377/ed466c76-d1b6-11e6-82ab-56519fae763d.png)

## [This.url uses private this._url](https://github.com/opentsdb-js/client/blob/master/lib/index.js#L281):
![https://github.com/opentsdb-js/client/blob/master/lib/index.js#L281](https://cloud.githubusercontent.com/assets/1396559/21623414/2040cca2-d1b7-11e6-9e70-ef3c68916dad.png)

## [This._url uses urlFactory](https://github.com/opentsdb-js/client/blob/362a82af8bc1480a1184f68bc0d130348653c5da/lib/index.js#L79)
![https://github.com/opentsdb-js/client/blob/362a82af8bc1480a1184f68bc0d130348653c5da/lib/index.js#L79](https://cloud.githubusercontent.com/assets/1396559/21623470/5fddeaa2-d1b7-11e6-8c95-fc338b6d7c30.png)

## [urlFactory is just opentsdb-url](https://github.com/opentsdb-js/client/blob/362a82af8bc1480a1184f68bc0d130348653c5da/lib/index.js#L40)
![https://github.com/opentsdb-js/client/blob/362a82af8bc1480a1184f68bc0d130348653c5da/lib/index.js#L40](https://cloud.githubusercontent.com/assets/1396559/21623496/77eb450e-d1b7-11e6-8fcb-230dcbc0c37e.png)

## [opentsdb-url appears to hard-code http](https://github.com/opentsdb-js/url/blob/master/lib/index.js#L68) 
![https://github.com/opentsdb-js/url/blob/master/lib/index.js#L68](https://cloud.githubusercontent.com/assets/1396559/21623536/b49c00a6-d1b7-11e6-9ba2-d9a0aa175d25.png)

**Comment by kgryte** [comment]
@valgaze Thanks for this issue and the screenshots. Closing this issue in favor of opentsdb-js/url#2.
